Ui
SPS-Coding-Projects-Society/The-Board pull request #7
Opened 2020-11-16 13:12 UTC by YoshiS214

Please change streamPage.dart
AppTabBar should be used for home of materialapp in main.dart

2020-11-16 13:23 UTC, ColtonZ commented on the_board/lib/main.dart
> +  /*
We can just delete this stuff

2020-11-16 13:24 UTC, ColtonZ commented on the_board/lib/pages/workroomPage.dart
> +      initialRoute: '/',
can we change the name of the route from / to something like /chatsList (or similar)?

2020-11-16 13:24 UTC, ColtonZ commented on the_board/lib/pages/workroomPage.dart
> +  final List workrooms = [
Great - will get back to you on how we get that from the messaging group

2020-11-16 13:25 UTC, ColtonZ commented on the_board/lib/pages/workroomPage.dart
> +                              TextStyle(color: Colors.grey[700]), // Last chat
Ideally at some point for all this theming, we'll write a themes.dart bit to keep consistency

2020-11-16 13:26 UTC, ColtonZ requested changes
Looks great! But please can you add comments to the code.

2020-11-16 19:43 UTC, YoshiS214 commented
I changed some parts and added some comments.
Is this a little bit better?

2020-11-23 12:51 UTC, ColtonZ approved these changes

2020-11-23 12:52 UTC, merged